name: '🛠 Merge Request Checks'
description: 'Checks if MR is clean'
inputs:
  node-version:
    description: 'Version of node'
    required: true
    default: '20'
runs:
  using: 'composite'
  steps:
    - name: Node Setup
      uses: dfcors/pipeline/.github/actions/node@master
      with:
        node-version: ${{ inputs.node-version }}
    - name: 🚨 Run Linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
    - name: 🛠 Build
      run: yarn build
      shell: bash
