name: 🚀 Deploy DO App
description: 'Deploys an application to Digital Ocean Apps Platform and sets up doctl for further commands.'
inputs:
  app_name:
    description: 'Name of the application to deploy.'
    required: true
  token:
    description: 'Digital Ocean API token.'
    required: true
  env_file:
    description: 'Path to the environment file to update.'
    required: true
    default: '.env.production'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Update GIT_TAG in environment
      shell: bash
      run: |
        if grep -q "^GIT_TAG=" "${{ inputs.env_file }}"; then
          sed -i "s/^GIT_TAG=.*/GIT_TAG=${{ github.ref }}/" "${{ inputs.env_file }}"
        else
          echo "GIT_TAG=${{ github.ref }}" >> "${{ inputs.env_file }}"
        fi

    - name: 🚀 Deploy to Digital Ocean
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: ${{ inputs.app_name }}
        token: ${{ inputs.token }}

    - name: Setup doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.token }}
