name: 🚀 Deploy DO App
description: 'Deploys an application to Digital Ocean Apps Platform and sets up doctl for further commands.'
inputs:
  app_name:
    description: 'Name of the application to deploy.'
    required: true
  token:
    description: 'Digital Ocean API token.'
    required: true
  env_file:
    description: 'Path to the environment file to update.'
    required: true
    default: '.env.production'
  pipeline_token:
    description: 'Pipeline Token to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update GIT_TAG in environment
      shell: bash
      run: |
        if grep -q "^GIT_TAG=" "${{ inputs.env_file }}"; then
          sed -i "s/^GIT_TAG=.*/GIT_TAG=${{ github.ref_name }}/" "${{ inputs.env_file }}"
        else
          sed -i "$ a\\
          GIT_TAG=${{ github.ref_name }}
          " "${{ inputs.env_file }}"
        fi

    - name: Commit Tag Version to Environment File
      shell: bash
      run: |
          git config --local user.email "actions@digitalforge.rs"
          git config --local user.name "Digital Forge"
          git add "${{ inputs.env_file }}"
          git commit -m "action: release version ${{ github.ref_name }}" || echo "Nothing to commit" 

    - name: Push changes to repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.pipeline_token }}
        branch: release
        repository: ${{ github.repository }}
        force: true

    - name: 🚀 Deploy to Digital Ocean
      uses: digitalocean/app_action@v1.1.6
      with:
        app_name: ${{ inputs.app_name }}
        token: ${{ inputs.token }}

    - name: Setup doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.token }}
